### ISSUE TITLE
Integrating with a separeted front-end

### ISSUE THREAD

**Issue by fhorray** [divyam234/next-auth-hono-react#3]
I'm facing a problem where I created my backend with honojs and integrated authjs, but I don't know how to integrate a custom sign-in page since all providers and authjs config is inside my backend app and I'm working with a separeted front-end, so I can't map the providers to create a custom sign-in page as authjs documentation says ([](https://authjs.dev/guides/pages/signin)), and when I try to create a custom page in my front-end I keep getting error that I dont even know how to solve, can someone help me?

this is the hono/authjs config I created:

```js

"use client";

import React from "react";

import { SessionProvider, authConfigManager } from "@hono/auth-js/react";

import { QueryClient, QueryClientProvider } from "react-query";

const queryClient = new QueryClient();

authConfigManager.setConfig({
  baseUrl: "http://127.0.0.1:3001",
  basePath: "/v1/auth",
  credentials: "include",
});

export const ClientLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <SessionProvider>
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    </SessionProvider>
  );
};
```

and this is my backend config:

```js
export const getAuthConfig = (c: Context): AuthConfig => {
  // connect to db
  const sql = neon(c.env.DATABASE_URL);
  const db = drizzle(sql);

  const providers = [
    Google({
      clientId: c.env.GOOGLE_CLIENT_ID,
      clientSecret: c.env.GOOGLE_CLIENT_SECRET,
    }),
    Resend,
  ];

  return {
    secret: c.env.AUTH_SECRET,
    // remove the line in production
    trustHost: true,
    adapter: DrizzleAdapter(db, {
      usersTable: users,
      accountsTable: accounts,
      sessionsTable: sessions,
      verificationTokensTable: verificationTokens,
    }),
    providers,
    events: { ... },
    callbacks: { ... },
    basePath: "/v1/auth",
    session: {
      strategy: "database",
    },
    pages: {
      signIn: "http://localhost:3000/login",
    },
  };
};

```

and my custom login page inside my front-end app is like this:

```js
const LoginForm = () => {
  const session = useSession();

  return (
    <section className="w-full h-screen flex items-center justify-center">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle className="text-2xl">Login</CardTitle>
          <CardDescription>
            Enter your email below to login to your account.
          </CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4">
          <Button className="w-full" onClick={(e) => signIn()}>
            Sign in
          </Button>
          <Button className="w-full" onClick={() => signIn("google")}>
            Google
          </Button>
        </CardContent>
      </Card>
    </section>
  );
};

export default LoginForm;
```

**Comment by divyam234** [comment]
@fhorray  Cross domain setup is bit of a headache to set up with auth.js.First you have to change the default cookies and set 
``sameSite: "none"`` for all of them and add ``allowHeaders: ["Content-Type", "x-auth-return-redirect", "Authorization"]`` this in cors middleware.

Also when you are using signIn function make sure to set redirect to false so that you can get callbackUrl in response without auto redirecting. And open this callbackUrl in separate popup window to maintain current page flow.

**Comment by fhorray** [comment]
@divyam234 I implemented my  index.ts config like this inside my backend:


```js

import { Hono } from "hono";
import { authHandler, initAuthConfig, verifyAuth } from "@hono/auth-js";
import { getAuth, getAuthConfig } from "@/auth";
import { Env } from "types/bindings";

// ROUTES
import users from "@routes/users";
import { cors } from "hono/cors";

const app = new Hono<{ Bindings: Env }>().basePath("/v1");

app.use(
  "*",
  cors({
    origin: (origin) => origin,
    allowHeaders: [
      "Content-Type",
      "Authorization",
      "x-auth-return-redirect",
    ],
    credentials: true,
  })
);

app.use("*", initAuthConfig(getAuthConfig));
app.use("/auth/*", authHandler());
app.use("/*", verifyAuth());

app.route("/users", users); // logic for creating, updating, deleting users.

export default app;


```


when I click on "sign in" button it goes to the authjs login page, and I'm able to login and retrieve the session Information inside my front-end, but it just works if I login inside the default login page.

But I want to build my own custom signin page inside my front-end, I dont want to use the default authjs page. 

when I try to use:

```js
 onClick={() => signIn("google" {redirect: false)}
 ```
 
it goes to the default authjs login page with a csrf missing error message, ("/v1/auth/signin?error=MissingCSRF"). I think its time to change the auth lib cus I cant make this work hahahah 😣

**Comment by Mag-codes** [comment]
But did this work out I've tried this but I am still encountering the same error 
![image](https://github.com/user-attachments/assets/def5249e-14fe-4fd6-9f4e-0ee1541f68d4)

Any support would be high appreciated
